"""EXP-034 独立评估 worker；固定既有权重、输入身份与随机流，支持断点续跑。"""
import argparse
import copy
import gc
import os
import time
from pathlib import Path
from types import SimpleNamespace

from rpcf.exp033_common import read_json, write_json, file_hash, fingerprint


def source_paths(manifest, task):
    from rpcf.exp031 import checkpoint, attack_path
    ds, model, seed = task['dataset'], task['model'], task['seed']
    src, ext = manifest['source_run'], manifest['external_run']
    method = task.get('method', 'madry') if task['kind']=='raw' else 'madry'
    run = ext if method=='clean' else src
    cp = checkpoint(run,ds,model,seed,method)
    if method=='clean': cp=cp.replace('_clean_eps0.03_','_clean_eps0_')
    paths = dict(classifier=cp)
    if method != 'clean':
        paths['source_audit']=f'logs/exp032/{ext}/audit/{ds}_{model}_seed{seed}.json'
    if task['kind']=='external':
        for name in task['purifiers']:
            paths[f'purifier_{name}']=f'checkpoints/exp032/{ext}/{ds}_seed{seed}_{name}.pth'
        for attack in task['attacks']:
            paths[f'attack_{attack}']=(f'ad_data/exp032/{ext}/{ds}_{model}_seed{seed}_madry_pgd_l2.pth'
                if attack=='pgd_l2' else attack_path(src,ds,model,seed,'madry',attack))
    elif task['kind'] in ('calibrate','structure','timing'):
        paths['config']='configs/thubenchmark/PTR3d_8_2048_rank25_3d_interpolate.yaml'
        paths['reference_calibration']=f"logs/exp033/{manifest['structure_run']}/metrics/calibrate_seed{seed}.json"
        paths['attack_pgd']=attack_path(src,ds,model,seed,'madry','pgd')
        if task['kind']!='calibrate':
            paths['calibration']=str(Path(manifest['run_dir'])/'metrics'/f"{task['calibration_task']}.json")
    return paths


def snapshot(paths):
    result={}
    for key,name in paths.items():
        p=Path(name);stat=p.stat()
        result[key]=dict(path=str(p),size=stat.st_size,mtime_ns=stat.st_mtime_ns,sha256=file_hash(p))
    return result


def load_context(manifest, task):
    from rpcf.exp032_common import load_condition
    args=SimpleNamespace(dataset=task['dataset'],model=task['model'],seed=task['seed'],fold=0,
        sample_num=512,run_id=manifest['external_run'],source_run=manifest['source_run'])
    data,info,train,val,clean,labels,indices,split=load_condition(args)
    n=manifest['sample_num']
    return SimpleNamespace(args=args,data=data,info=info,train=train,val=val,clean=clean[:n],labels=labels[:n],indices=indices[:n],split=split)


def load_attack(ctx, attack, path, classifier_path):
    """只接受本条件的 Madry 攻击，核验身份/权重/参数和实际扰动范数。"""
    from rpcf.exp032_common import load_payload, align_payload, norm_audit
    source=load_payload(path);meta=source['meta']
    for key,val in dict(dataset=ctx.args.dataset,model=ctx.args.model,seed=ctx.args.seed,fold=0,attack=attack,method_tag='madry',source_split='test').items():
        if meta.get(key)!=val: raise ValueError(f'Attack provenance differs: {key}')
    if Path(meta['checkpoint_path']).resolve()!=Path(classifier_path).resolve():
        raise ValueError('Attack was not generated by the selected Madry checkpoint')
    if meta.get('checkpoint_sha256') and meta['checkpoint_sha256']!=file_hash(classifier_path):
        raise ValueError('Attack checkpoint contents differ')
    protocol=meta['attack_protocol']
    specs={
        'fgsm':dict(norm='Linf',eps=.03,steps=1),
        'pgd':dict(norm='Linf',eps=.03,steps=200,alpha=2/255,random_start=False),
        'autoattack':dict(norm='Linf',eps=.03,version='standard'),
        'cw':dict(norm='L2',steps=200,lr=.1,c=10000,kappa=1),
        'pgd_l2':dict(norm='L2',eps=1.,steps=200,alpha=.1,restarts=5,random_start=True),
    }
    for key,val in specs[attack].items():
        if protocol.get(key)!=val: raise ValueError(f'Attack protocol differs: {attack}/{key}')
    aligned=align_payload(source,ctx.indices,ctx.labels,ctx.clean)
    adv=aligned['adversarial']
    norm=norm_audit(ctx.clean,adv,protocol['norm'],None if attack=='cw' else protocol['eps'])
    return adv,protocol,norm


def row(ctx, method, attack, cp, ap, sections, **extra):
    from rpcf.exp032_common import metric_row
    return metric_row(ctx.args,method,attack,cp,ap,ctx.labels,sections=sections,**extra)


def adaptive_predictions(manifest, task, ctx, model, root, identity, label, subjects=None):
    """复用原 PGD-10 更新式；EA 每个攻击样本绑定自己的 subject id。

    不保存重复的完整 adversarial 张量。保存逐样本范数/hash、预测和RNG；
    断点另保存模型state，以保留EA/约束层forward可能产生的状态变化。
    """
    import torch
    from rpcf.core import seed_everything
    from rpcf.exp032_common import predict, norm_audit
    from rpcf.exp032_external_pgd10 import pgd10
    from rpcf.exp033_worker import load_state, save_state, tensor_hash
    path=root/'partials'/f"{task['task_id']}_{label}.pth"
    device=next(model.parameters()).device
    seed_everything(task['seed'])
    state=load_state(path,identity,dict(predictions=[],diagnostics=[],model_state=None))
    if state['model_state'] is not None: model.load_state_dict(state['model_state'])
    for i in range(len(state['predictions']),len(ctx.clean)):
        if subjects is not None: model.set_subject_ids(subjects[i:i+1].to(device))
        adv=pgd10(model,ctx.clean[i:i+1],ctx.labels[i:i+1],device)
        norm=norm_audit(ctx.clean[i:i+1],adv,'Linf',.03)
        pred=predict(model,adv,1,None if subjects is None else subjects[i:i+1])
        state['predictions'].extend(pred)
        state['diagnostics'].append(dict(source_index=ctx.indices[i],adv_sha256=tensor_hash(adv),**norm))
        if (i+1)%16==0 or i+1==len(ctx.clean):
            state['model_state']={k:v.detach().cpu().clone() for k,v in model.state_dict().items()}
            save_state(path,identity,state)
            print(f'ADAPTIVE {label} {i+1}/{len(ctx.clean)}',flush=True)
    return state['predictions'],state['diagnostics']


def external(manifest, task, ctx, root, paths, identity):
    import torch
    from torch import nn
    from rpcf.core import seed_everything
    from rpcf.exp032_common import load_classifier,load_payload,predict,state_changes
    from rpcf.exp032_external_pgd10 import ADAPTIVE_PROTOCOL
    from rpcf.exp032_purifiers import EEGReformer
    rows,diagnostics,audits=[],{},{}
    for purifier_name in task['purifiers']:
        # 每个组合从同一checkpoint重新加载，避免前一净化器的forward副作用污染后一组合。
        seed_everything(task['seed'])
        classifier,_,classifier_path=load_classifier(ctx.args,ctx.info,'madry',ctx.data)
        device=next(classifier.parameters()).device
        artifact=load_payload(paths[f'purifier_{purifier_name}']);meta=artifact['meta']
        for key,val in dict(dataset=task['dataset'],seed=task['seed'],fold=0,method=purifier_name).items():
            if meta.get(key)!=val: raise ValueError(f'Purifier provenance differs: {key}')
        purifier=EEGReformer(purifier_name,meta['low'],meta['high']).to(device)
        purifier.load_state_dict(artifact['state_dict'])
        model=nn.Sequential(purifier,classifier).eval()
        for p in model.parameters():p.requires_grad_(False)
        initial={k:v.detach().cpu().clone() for k,v in model.state_dict().items()}
        cp=predict(model,ctx.clean,manifest['evaluation_batch_size'])
        if cp!=predict(model,ctx.clean,manifest['evaluation_batch_size']):
            raise ValueError('Repeated clean predictions differ')
        audits[purifier_name]=dict(after_clean=state_changes(initial,model),classifier_path=classifier_path,purifier_meta=meta)
        for attack in task['attacks']:
            adv,protocol,norm=load_attack(ctx,attack,paths[f'attack_{attack}'],classifier_path)
            ap=predict(model,adv,manifest['evaluation_batch_size'])
            sections=(['main'] if attack=='pgd' else [])+(['cross_attack'] if task['adaptive'] else [])
            rows.append(row(ctx,f'madry_{purifier_name}',attack,cp,ap,sections,
                evaluation='nonadaptive_purification',attack_protocol=protocol,norm_audit=norm,
                classifier_method='madry',evaluation_batch_size=manifest['evaluation_batch_size']))
            print(f'EXTERNAL {purifier_name}/{attack} n={len(ctx.indices)}',flush=True)
            del adv
        if task['adaptive']:
            ap,diagnostics[purifier_name]=adaptive_predictions(manifest,task,ctx,model,root,
                fingerprint(dict(identity=identity,purifier=purifier_name)),purifier_name)
            rows.append(row(ctx,f'madry_{purifier_name}','pgd10',cp,ap,['adaptive'],
                evaluation='adaptive_exact_gradient',attack_protocol=dict(ADAPTIVE_PROTOCOL),classifier_method='madry',
                evaluation_batch_size=1))
        audits[purifier_name]['after_all']=state_changes(initial,model)
        del model,classifier,purifier,artifact,initial
        gc.collect()
        if torch.cuda.is_available():torch.cuda.empty_cache()
    return dict(rows=rows,adaptive_sample_diagnostics=diagnostics,model_audits=audits)


def raw(manifest,task,ctx,root,paths,identity):
    import torch
    from rpcf.exp032_common import load_classifier,predict,state_changes
    from rpcf.exp032_evaluate import ea_inputs
    from rpcf.exp032_external_pgd10 import ADAPTIVE_PROTOCOL
    from rpcf.exp033_worker import tensor_hash
    model,ea_test,_=load_classifier(ctx.args,ctx.info,task['method'],ctx.data)
    subjects=None
    standard_hash=tensor_hash(ctx.clean)
    if ea_test is not None:
        ctx.clean,subjects=ea_inputs(ea_test,ctx.indices,ctx.labels)
    model.eval()
    for p in model.parameters():p.requires_grad_(False)
    initial={k:v.detach().cpu().clone() for k,v in model.state_dict().items()}
    cp=predict(model,ctx.clean,manifest['raw_evaluation_batch_size'],subjects)
    if cp!=predict(model,ctx.clean,manifest['raw_evaluation_batch_size'],subjects):
        raise ValueError('Repeated baseline clean predictions differ')
    clean_changes=state_changes(initial,model)
    ap,diagnostics=adaptive_predictions(manifest,task,ctx,model,root,identity,task['method'],subjects)
    protocol=dict(ADAPTIVE_PROTOCOL,gradient='exact_through_classifier',reference='EXP-031 BPDA PGD-10 optimization settings')
    return dict(rows=[row(ctx,task['method'],'pgd10',cp,ap,['adaptive'],evaluation='classifier_whitebox',
                         attack_protocol=protocol,evaluation_batch_size=1,clean_evaluation_batch_size=manifest['raw_evaluation_batch_size'])],
                sample_diagnostics=diagnostics,standard_input_sha256=standard_hash,attack_input_sha256=tensor_hash(ctx.clean),
                subject_ids=subjects.tolist() if subjects is not None else None,
                input_coordinate_system='EA前原始缓存值（沿用EXP-032 ea_inputs）' if subjects is not None else 'standardized EEG',
                state_changes_after_clean=clean_changes,state_changes_after_all=state_changes(initial,model))


def reconstruct(sample,spec,device):
    """逐式沿用EXP-033公共插值/逆变换及计时边界，仅替换标准分解调用。"""
    import numpy as np
    import torch
    import yaml
    from purify import fft_resample,ToInterpolatedGrid,dataset_channel_location_dicts
    from TN.opt import Config
    from rpcf.exp034_structures import decompose
    config=Config()
    for k,v in yaml.safe_load(Path('configs/thubenchmark/PTR3d_8_2048_rank25_3d_interpolate.yaml').read_text()).items():
        setattr(config,k,v)
    if config.strategy!='3d_interpolate':raise ValueError('Common representation changed')
    locations=dataset_channel_location_dicts['thubenchmark']
    if device.type=='cuda':torch.cuda.synchronize(device)
    start=time.perf_counter()
    data=sample.detach().cpu().clone().permute(1,2,0)
    grid=ToInterpolatedGrid(locations)
    pre=torch.from_numpy(grid(eeg=data.squeeze().numpy())['eeg']).permute(1,2,0).float()
    target_len=round(2**np.ceil(np.log2(data.shape[1])+config.c))
    pre=fft_resample(pre,target_len=target_len).to(device)
    if device.type=='cuda':torch.cuda.synchronize(device)
    decomposition_start=time.perf_counter()
    rebuilt,diagnostic=decompose(pre,spec)
    if device.type=='cuda':torch.cuda.synchronize(device)
    decomposition_time=time.perf_counter()-decomposition_start
    restored=fft_resample(rebuilt.detach().clone(),target_len=sample.shape[-1])
    grid=ToInterpolatedGrid(locations)
    purified=torch.from_numpy(grid.reverse(eeg=restored.permute(2,0,1).cpu().numpy())['eeg']).unsqueeze(0).float()
    if device.type=='cuda':torch.cuda.synchronize(device)
    if purified.shape!=sample.shape or not torch.isfinite(purified).all():raise ValueError('Invalid reconstructed EEG')
    diagnostic.update(decomposition_seconds=decomposition_time,total_seconds=time.perf_counter()-start)
    return purified,diagnostic


def calibrate(manifest,task,ctx,root,paths,identity):
    from purify import interpolate
    from utils.experiment_artifacts import eeg_classification_collate
    from utils.reproducibility import stable_subset_indices
    from rpcf.exp034_structures import candidates,decompose
    from rpcf.exp033_structures import select_candidate
    from rpcf.exp033_worker import load_state,save_state,tensor_hash
    import torch
    device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    # smoke也先取正式32个validation索引，再截取前缀，避免改变抽样规则。
    positions,selection_seed=stable_subset_indices(len(ctx.val),min(32,len(ctx.val)),task['seed'],0)
    reference=read_json(paths['reference_calibration'])
    if positions!=reference['validation_indices']:raise ValueError('EXP-033 validation indices changed')
    full_x,_=eeg_classification_collate([ctx.val[i] for i in positions])
    if tensor_hash(full_x)!=reference['validation_input_sha256']:raise ValueError('EXP-033 validation inputs changed')
    positions=positions[:manifest['validation_sample_num']]
    x=full_x[:len(positions)]
    args=SimpleNamespace(dataset='thubenchmark',model='eegnet',seed=task['seed'],visualize=False,config=paths['config'])
    tensors=[interpolate(args,item,250).to(device) for item in x]
    partial=root/'partials'/f"{task['task_id']}.pth"
    state=load_state(partial,identity,dict(scored={},selected={}))
    for budget in (25,30):
        key=str(budget);scored=state['scored'].setdefault(key,[])
        specs=candidates(budget)
        for spec in specs[len(scored):]:
            errors=[]
            for tensor in tensors:
                rebuilt,_=decompose(tensor,spec)
                errors.append(float((rebuilt-tensor).norm()/tensor.norm().clamp_min(1e-20)))
            scored.append(dict(spec,mean_relative_error=sum(errors)/len(errors)))
            save_state(partial,identity,state)
            print(f'CALIBRATE tr_time/{budget} {len(scored)}/{len(specs)}',flush=True)
        state['selected'][key]=select_candidate(scored)
        save_state(partial,identity,state)
    return dict(rows=[],validation_indices=positions,validation_input_sha256=tensor_hash(x),
                selection_seed=selection_seed,selection_split='validation',**state)


def structure(manifest,task,ctx,root,paths,identity):
    import torch
    from rpcf.exp032_common import load_classifier,predict
    from rpcf.exp033_worker import load_state,save_state,tensor_hash
    spec=read_json(paths['calibration'])['selected'][str(task['budget_rank'])]
    model,_,cp_path=load_classifier(ctx.args,ctx.info,'madry',ctx.data)
    device=next(model.parameters()).device
    adv,protocol,norm=load_attack(ctx,'pgd',paths['attack_pgd'],cp_path)
    partial=root/'partials'/f"{task['task_id']}.pth"
    state=load_state(partial,identity,dict(cp=[],ap=[],diagnostics=[]))
    for i in range(len(state['cp']),len(ctx.clean)):
        pc,dc=reconstruct(ctx.clean[i],spec,device)
        pa,da=reconstruct(adv[i],spec,device)
        state['cp'].extend(predict(model,pc.unsqueeze(0),1))
        state['ap'].extend(predict(model,pa.unsqueeze(0),1))
        state['diagnostics'].append(dict(source_index=ctx.indices[i],clean_mse=float((pc-ctx.clean[i]).square().mean()),
            adv_mse_to_clean=float((pa-ctx.clean[i]).square().mean()),removed_mse=float((pa-adv[i]).square().mean()),
            clean_sha256=tensor_hash(pc),adv_sha256=tensor_hash(pa),actual_rank=da['actual_rank'],actual_parameters=da['actual_parameters']))
        if (i+1)%8==0 or i+1==len(ctx.clean):
            save_state(partial,identity,state);print(f'STRUCTURE tr_time/{task["budget_rank"]} {i+1}/{len(ctx.clean)}',flush=True)
    mean=lambda key:sum(d[key] for d in state['diagnostics'])/len(state['diagnostics'])
    r=row(ctx,'tr_time','pgd',state['cp'],state['ap'],['structure'],evaluation='nonadaptive_purification',
          attack_protocol=protocol,budget_rank=task['budget_rank'],parameters=spec['parameters'],actual_rank=spec['rank'],
          budget_deviation=spec['budget_deviation'],budget_exception=False,clean_mse_mean=mean('clean_mse'),
          adv_mse_to_clean_mean=mean('adv_mse_to_clean'),removed_mse_mean=mean('removed_mse'))
    return dict(rows=[r],spec=spec,norm_audit=norm,sample_diagnostics=state['diagnostics'])


def timing(manifest,task,ctx,root,paths,identity):
    import torch
    from statistics import mean,median
    from rpcf.exp033_worker import assert_exclusive
    device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    if device.type!='cuda' and not manifest['smoke']:raise ValueError('Formal timing needs CUDA')
    spec=read_json(paths['calibration'])['selected'][str(task['budget_rank'])]
    adv,protocol,_=load_attack(ctx,'pgd',paths['attack_pgd'],paths['classifier'])
    assert_exclusive(device)
    reconstruct(ctx.clean[0],spec,device)
    diagnostics=[]
    for label,inputs in [('clean',ctx.clean[:8]),('adv',adv[:8])]:
        for i,sample in enumerate(inputs):
            assert_exclusive(device)
            if device.type=='cuda':torch.cuda.empty_cache();torch.cuda.reset_peak_memory_stats(device)
            _,d=reconstruct(sample,spec,device)
            d.update(input_kind=label,source_index=ctx.indices[i],peak_memory_bytes=torch.cuda.max_memory_allocated(device) if device.type=='cuda' else 0)
            diagnostics.append(d)
    assert_exclusive(device)
    r=dict(dataset=task['dataset'],model=task['model'],seed=task['seed'],fold=0,scope='timing_subset',
        method='tr_time',attack='pgd',evaluation='timing',sections=['structure'],budget_rank=task['budget_rank'],
        sample_num=len(diagnostics),parameters=spec['parameters'],attack_protocol=protocol,
        decomposition_seconds_mean=mean(d['decomposition_seconds'] for d in diagnostics),
        total_seconds_mean=mean(d['total_seconds'] for d in diagnostics),total_seconds_median=median(d['total_seconds'] for d in diagnostics),
        peak_memory_bytes=max(d['peak_memory_bytes'] for d in diagnostics),native_compression_ratio=ctx.clean[0].numel()/spec['parameters'],
        tensor_compression_ratio=225280/spec['parameters'],device=torch.cuda.get_device_name(device) if device.type=='cuda' else 'CPU_SMOKE')
    return dict(rows=[r],spec=spec,samples=diagnostics)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run-dir',required=True);parser.add_argument('--task-id',required=True)
    args=parser.parse_args();root=Path(args.run_dir)
    from rpcf.exp034 import verify,check_result
    from rpcf.core import seed_everything
    from rpcf.exp033_worker import tensor_hash
    import torch
    manifest,tasks=verify(root)
    task=next(t for t in tasks if t['task_id']==args.task_id)
    if Path(task['output_path']).exists():
        check_result(manifest,task,read_json(task['output_path']))
        print('Existing validated output; no overwrite',flush=True);return
    torch.set_num_threads(2)
    seed_everything(task['seed'])
    paths=source_paths(manifest,task);sources=snapshot(paths)
    if 'source_audit' in paths:
        method=task['method'] if task['kind']=='raw' else 'madry'
        audit=read_json(paths['source_audit'])
        check=next(c for c in audit['checks'] if c['method']==method)
        if check['checkpoint_sha256']!=sources['classifier']['sha256'] or Path(check['checkpoint_path']).resolve()!=Path(paths['classifier']).resolve():
            raise ValueError('Checkpoint differs from accepted EXP-032 source audit')
    ctx=load_context(manifest,task)
    identity=fingerprint(dict(task=task,sources=sources,clean_sha256=tensor_hash(ctx.clean),indices=ctx.indices))
    result=globals()[task['kind']](manifest,task,ctx,root,paths,identity)
    result.update(experiment_id='EXP-034',run_id=manifest['run_id'],task_id=task['task_id'],task_fingerprint=fingerprint(task),
        smoke=manifest['smoke'],dataset=task['dataset'],model=task['model'],seed=task['seed'],fold=0,
        source_indices=ctx.indices,labels=ctx.labels.tolist(),split=ctx.split,sources=sources,input_sha256=tensor_hash(ctx.clean))
    check_result(manifest,task,result)
    write_json(task['output_path'],result)
    print(f'COMPLETE {task["task_id"]}',flush=True)


if __name__=='__main__':main()
